### ISSUE TITLE
Error when pulling submodules

### ISSUE THREAD

**Issue by rachelambda** [dylanaraps/kiss-submodule-links#1]
I tried this solution in my repo, however I run into an issue when running `kiss u`

I have an entire directory in my path symlinked to a directory in another repo, which is what causes errors. (`grepo/xorg` was symlinked to `repo/xorg`)

It pulls the super/master/head repo which is fine, however when running `git submodule update --remote --init -f` it checks out the submodule to a specific sha1 hash, this means that when it later cd's to the symlinked directory it will try to run `git pull` in the symlinked directory, causing it to fail with the following message.

```
You are not currently on a branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.

    git pull <remote> <branch>

```

I understand that I can simply create a directory and then link all subdirectories in there, however it might be good to add this info somewhere to make sure no one else has to figure this out by themself.

**Comment by dylanaraps** [comment]
You're using the submodule in your `KISS_PATH`? Or am I misunderstood?

**Comment by rachelambda** [comment]
basically, one of the directories in KISS_PATH was a symlink to a directory in a submodule, this means that kiss will cd into the symlink and then run `git pull`, sorry for not being clear.

**Comment by rachelambda** [comment]
basically, do not do
```sh
ls -s <path to dir> <dir name>
```
if that dir is going in KISS_PATH, instead do
```sh
mkdir <dir name>
cd <dir name>
for pkg in <path to dir>/*; do ln -s "$pkg" "${pkg##*/}; done
```

**Comment by dylanaraps** [comment]
Should be fixed in: https://github.com/kisslinux/kiss/commit/f552a75427f5b34987181511b6016e59797afda5 Let me know.
